import { Button, GridBox, HorizontalBox, VerticalBox } from "std-widgets.slint";

component RadixBox {
    callback clicked;

    in property <string> value: "0";
    in property <string> mode;
    in property <bool> selected;

    Rectangle {
        border-color: selected ? white : gray;
        border-width: 1px;

        TouchArea {
            HorizontalBox {
                Text {
                    text: "\{mode}: \{value}";
                    overflow: elide;
                    font-size: 16px;
                }
            }

            clicked => {
                root.clicked();
            }
        }
    }
}

export component AppWindow inherits Window {
    pure callback update_screen(string);
    pure callback update_radix_boxes();
    pure callback backspace();
    pure callback check_valid_keypress(string) -> bool;

    in-out property <string> screen: "0";
    in-out property <bool> dirty;

    out property <string> mode: "Dec";

    in property <string> bin: "0";
    in property <string> dec: "0";
    in property <string> hex: "0";
    in property <string> oct: "0";

    function clear_screen() {
        self.screen = "0";
    }

    title: "Radix";
    width: 400px;
    default-font-family: "Mononoki Nerd Font";

    FocusScope {
        init => {
            self.focus();
        }
        key-pressed(event) => {
            // if (event.modifiers.control) {
            //     debug("control was pressed during this event");
            // }
            if (event.text == Key.Backspace) {
                root.backspace();
                root.update_radix_boxes();
            } else if (event.text == Key.Escape) {
                root.clear_screen();
                root.update_radix_boxes();
            } else {
                if root.check_valid_keypress(event.text) {
                    root.update_screen(event.text);
                    root.update_radix_boxes();
                }
            }
            accept
        }
    }

    VerticalBox {
        Rectangle {
            background: black;
            padding: 150px;
            border-radius: 20px;
            Text {
                width: parent.width;
                text: "\{root.screen}";
                color: greenyellow;
                font-size: 32px;
                overflow: elide;
                horizontal-alignment: center;
            }
        }

        RadixBox {
            mode: "Dec";
            value: root.dec;
            selected: root.mode == self.mode;
            clicked => {
                if !self.selected {
                    root.mode = self.mode;
                    root.dirty = true;
                }
            }
        }

        RadixBox {
            mode: "Hex";
            value: root.hex;
            selected: root.mode == self.mode;
            clicked => {
                if !self.selected {
                    root.mode = self.mode;
                    root.dirty = true;
                }
            }
        }

        RadixBox {
            mode: "Oct";
            value: root.oct;
            selected: root.mode == self.mode;
            clicked => {
                if !self.selected {
                    root.mode = self.mode;
                    root.dirty = true;
                }
            }
        }

        RadixBox {
            mode: "Bin";
            value: root.bin;
            selected: root.mode == self.mode;
            clicked => {
                if !self.selected {
                    root.mode = self.mode;
                    root.dirty = true;
                }
            }
        }

        GridBox {
            Button {
                text: "D";
                row: 0;
                enabled: root.mode == "Hex";
                clicked => {
                    root.update_screen(self.text);
                    root.update_radix_boxes();
                }
            }

            Button {
                text: "E";
                enabled: root.mode == "Hex";
                clicked => {
                    root.update_screen(self.text);
                    root.update_radix_boxes();
                }
            }

            Button {
                text: "F";
                enabled: root.mode == "Hex";
                clicked => {
                    root.update_screen(self.text);
                    root.update_radix_boxes();
                }
            }

            Button {
                text: "A";
                row: 1;
                enabled: root.mode == "Hex";
                clicked => {
                    root.update_screen(self.text);
                    root.update_radix_boxes();
                }
            }

            Button {
                text: "B";
                enabled: root.mode == "Hex";
                clicked => {
                    root.update_screen(self.text);
                    root.update_radix_boxes();
                }
            }

            Button {
                text: "C";
                enabled: root.mode == "Hex";
                clicked => {
                    root.update_screen(self.text);
                    root.update_radix_boxes();
                }
            }

            Button {
                text: "7";
                row: 2;
                enabled: root.mode != "Bin";
                clicked => {
                    root.update_screen(self.text);
                    root.update_radix_boxes();
                }
            }

            Button {
                text: "8";
                enabled: root.mode == "Dec" || root.mode == "Hex";
                clicked => {
                    root.update_screen(self.text);
                    root.update_radix_boxes();
                }
            }

            Button {
                text: "9";
                enabled: root.mode == "Dec" || root.mode == "Hex";
                clicked => {
                    root.update_screen(self.text);
                    root.update_radix_boxes();
                }
            }

            Button {
                text: "4";
                row: 3;
                enabled: root.mode != "Bin";
                clicked => {
                    root.update_screen(self.text);
                    root.update_radix_boxes();
                }
            }

            Button {
                text: "5";
                enabled: root.mode != "Bin";
                clicked => {
                    root.update_screen(self.text);
                    root.update_radix_boxes();
                }
            }

            Button {
                text: "6";
                enabled: root.mode != "Bin";
                clicked => {
                    root.update_screen(self.text);
                    root.update_radix_boxes();
                }
            }

            Button {
                text: "1";
                row: 4;
                clicked => {
                    root.update_screen(self.text);
                    root.update_radix_boxes();
                }
            }

            Button {
                text: "2";
                enabled: root.mode != "Bin";
                clicked => {
                    root.update_screen(self.text);
                    root.update_radix_boxes();
                }
            }

            Button {
                text: "3";
                enabled: root.mode != "Bin";
                clicked => {
                    root.update_screen(self.text);
                    root.update_radix_boxes();
                }
            }

            Button {
                text: "CE";
                row: 5;
                clicked => {
                    root.clear_screen();
                    root.update_radix_boxes();
                }
            }

            Button {
                text: "0";
                clicked => {
                    root.update_screen(self.text);
                    root.update_radix_boxes();
                }
            }

            Button {
                text: "<-";
                clicked => {
                    root.backspace();
                    root.update_radix_boxes();
                }
            }
        }
    }
}
