import { Button, GridBox, HorizontalBox, VerticalBox } from "std-widgets.slint";

component ModeBox {
    callback clicked;

    in property <string> value: "0";
    in property <string> mode;
    in property <bool> selected;

    Rectangle {
        border-color: selected ? white : gray;
        border-width: 1px;

        TouchArea {
            HorizontalBox {
                Text {
                    text: "\{mode}: \{value}";
                    // width: parent.width;
                    overflow: elide;
                    font-size: 16px;
                }
            }

            clicked => {
                root.clicked();
            }
        }
    }
}

export component AppWindow inherits Window {
    pure callback update();
    pure callback backspace();

    in-out property <string> label: "0";

    out property <bool> dirty;
    out property <string> mode: "Dec";

    in property <string> hex: "0";
    in property <string> oct: "0";
    in property <string> dec: "0";
    in property <string> bin: "0";

    function update_label(s: string) {
        if self.label == "0" || self.dirty {
            self.label = s;
            self.dirty = false;
        } else {
            self.label += s;
        }
    }

    function clear_label() {
        self.label = "0";
    }

    title: "Radix";
    width: 400px;
    default-font-family: "Mononoki Nerd Font";

    VerticalBox {
        Rectangle {
            background: black;
            padding: 150px;
            border-radius: 20px;
            Text {
                width: parent.width;
                text: "\{root.label}";
                color: greenyellow;
                font-size: 32px;
                overflow: elide;
                horizontal-alignment: center;
            }
        }

        ModeBox {
            mode: "Dec";
            value: root.dec;
            selected: root.mode == self.mode;
            clicked => {
                if !self.selected {
                    root.mode = self.mode;
                    root.dirty = true;
                }
            }
        }

        ModeBox {
            mode: "Hex";
            value: root.hex;
            selected: root.mode == self.mode;
            clicked => {
                if !self.selected {
                    root.mode = self.mode;
                    root.dirty = true;
                }
            }
        }

        ModeBox {
            mode: "Oct";
            value: root.oct;
            selected: root.mode == self.mode;
            clicked => {
                if !self.selected {
                    root.mode = self.mode;
                    root.dirty = true;
                }
            }
        }

        ModeBox {
            mode: "Bin";
            value: root.bin;
            selected: root.mode == self.mode;
            clicked => {
                if !self.selected {
                    root.mode = self.mode;
                    root.dirty = true;
                }
            }
        }

        GridBox {
            Button {
                text: "D";
                row: 0;
                enabled: root.mode == "Hex";
                clicked => {
                    root.update_label(self.text);
                    root.update();
                }
            }

            Button {
                text: "E";
                enabled: root.mode == "Hex";
                clicked => {
                    root.update_label(self.text);
                    root.update();
                }
            }

            Button {
                text: "F";
                enabled: root.mode == "Hex";
                clicked => {
                    root.update_label(self.text);
                    root.update();
                }
            }

            Button {
                text: "A";
                row: 1;
                enabled: root.mode == "Hex";
                clicked => {
                    root.update_label(self.text);
                    root.update();
                }
            }

            Button {
                text: "B";
                enabled: root.mode == "Hex";
                clicked => {
                    root.update_label(self.text);
                    root.update();
                }
            }

            Button {
                text: "C";
                enabled: root.mode == "Hex";
                clicked => {
                    root.update_label(self.text);
                    root.update();
                }
            }

            Button {
                text: "7";
                row: 2;
                enabled: root.mode != "Bin";
                clicked => {
                    root.update_label(self.text);
                    root.update();
                }
            }

            Button {
                text: "8";
                enabled: root.mode == "Dec" || root.mode == "Hex";
                clicked => {
                    root.update_label(self.text);
                    root.update();
                }
            }

            Button {
                text: "9";
                enabled: root.mode == "Dec" || root.mode == "Hex";
                clicked => {
                    root.update_label(self.text);
                    root.update();
                }
            }

            Button {
                text: "4";
                row: 3;
                enabled: root.mode != "Bin";
                clicked => {
                    root.update_label(self.text);
                    root.update();
                }
            }

            Button {
                text: "5";
                enabled: root.mode != "Bin";
                clicked => {
                    root.update_label(self.text);
                    root.update();
                }
            }

            Button {
                text: "6";
                enabled: root.mode != "Bin";
                clicked => {
                    root.update_label(self.text);
                    root.update();
                }
            }

            Button {
                text: "1";
                row: 4;
                clicked => {
                    root.update_label(self.text);
                    root.update();
                }
            }

            Button {
                text: "2";
                enabled: root.mode != "Bin";
                clicked => {
                    root.update_label(self.text);
                    root.update();
                }
            }

            Button {
                text: "3";
                enabled: root.mode != "Bin";
                clicked => {
                    root.update_label(self.text);
                    root.update();
                }
            }

            Button {
                text: "0";
                row: 5;
                clicked => {
                    root.update_label(self.text);
                    root.update();
                }
            }

            Button {
                text: "CE";
                clicked => {
                    root.clear_label();
                    root.update();
                }
            }

            Button {
                text: "<-";
                clicked => {
                    root.backspace();
                }
            }
        }
    }
}
